apiVersion: v2
appVersion: v2.9.0
description: Cloudchipr SaaS Platform Kubernetes Agent
icon: https://static.cloudchipr.io/logos/PNG/cloudchipr%20favicon%404x.png
home: https://github.com/cloudchipr/cloudchipr-resources
keywords:
  - Cloudchipr
  - Kubernetes
  - Metrics
kubeVersion: ">= 1.19.0-0"
name: c8r-agent
type: application
version: 2.11.0
