{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}
  namespace: {{ include "..namespace" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  C8R_API_KEY: {{ toString ( required "config.c8r_api_key is required" .Values.config.c8r_api_key ) | b64enc }}
  C8R_CLUSTER_ID: {{ toString ( required "config.c8r_cluster_id is required" .Values.config.c8r_cluster_id ) | b64enc }}
  C8R_CLOUD_ACCOUNT: {{ toString  ( required "config.c8r_cloud_account is required" .Values.config.c8r_cloud_account ) | b64enc }}
  C8R_CLUSTER_NAME: {{ toString ( required "config.c8r_cluster_name is required" .Values.config.c8r_cluster_name ) | b64enc }}
{{- end -}}
